import Mathlib
import S6Shortcuts

/-!
# Square-zero exchange flows

This file formalizes the unconditional algebraic content of Lemma 6.1 of the short-proof paper.
A square-zero endomorphism generates an additive one-parameter family of linear equivalences, and
an infinitesimally invariant bilinear form is invariant under the whole family.  The final section
applies the result to the finite `N` and `Q0` matrices certified in `S6Shortcuts`.

No assertion about the existence of a complex structure on the six-sphere is made here; the
analytic hypotheses of the proposed construction lie outside the scope of this module.
-/

namespace S6.SquareZeroExchange

section General

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]

/-- The linear exchange `1 + sN` generated by an endomorphism `N`. -/
def exchange (N : Module.End R M) (s : R) : Module.End R M :=
  1 + s • N

@[simp]
theorem exchange_zero (N : Module.End R M) : exchange N 0 = 1 := by
  simp [exchange]

@[simp]
theorem exchange_apply (N : Module.End R M) (s : R) (x : M) :
    exchange N s x = x + s • N x := by
  simp [exchange]

/-- Square-zero exchanges compose by adding their parameters. -/
theorem exchange_mul_exchange {N : Module.End R M} (hN : N * N = 0) (s t : R) :
    exchange N s * exchange N t = exchange N (s + t) := by
  ext x
  have hNN : N (N x) = 0 := by
    simpa [Module.End.mul_apply] using DFunLike.congr_fun hN x
  simp only [Module.End.mul_apply, exchange_apply, map_add, map_smul, hNN, smul_zero, add_zero]
  module

/-- A square-zero exchange as a linear equivalence. -/
def exchangeEquiv (N : Module.End R M) (hN : N * N = 0) (s : R) : M ≃ₗ[R] M :=
  LinearEquiv.ofLinear (exchange N s) (exchange N (-s))
    (by
      rw [← Module.End.mul_eq_comp, exchange_mul_exchange hN, add_neg_cancel, exchange_zero]
      rfl)
    (by
      rw [← Module.End.mul_eq_comp, exchange_mul_exchange hN, neg_add_cancel, exchange_zero]
      rfl)

@[simp]
theorem exchangeEquiv_toLinearMap {N : Module.End R M} (hN : N * N = 0) (s : R) :
    (exchangeEquiv N hN s).toLinearMap = exchange N s :=
  rfl

@[simp]
theorem exchangeEquiv_apply {N : Module.End R M} (hN : N * N = 0) (s : R) (x : M) :
    exchangeEquiv N hN s x = exchange N s x :=
  rfl

/-- The inverse of `E_s` is `E_{-s}`. -/
theorem exchangeEquiv_symm_toLinearMap {N : Module.End R M} (hN : N * N = 0) (s : R) :
    (exchangeEquiv N hN s).symm.toLinearMap = exchange N (-s) :=
  rfl

/-- The quadratic term forced by a square-zero skew operator vanishes. -/
theorem quadratic_term_eq_zero {N : Module.End R M} (hN : N * N = 0)
    (Q : LinearMap.BilinForm R M)
    (hskew : ∀ x y, Q (N x) y + Q x (N y) = 0) (x y : M) :
    Q (N x) (N y) = 0 := by
  have hNN : N (N y) = 0 := by
    simpa [Module.End.mul_apply] using DFunLike.congr_fun hN y
  simpa [hNN] using hskew x (N y)

/-- An infinitesimally invariant bilinear form is preserved by every square-zero exchange. -/
theorem exchange_preserves_bilin {N : Module.End R M} (hN : N * N = 0)
    (Q : LinearMap.BilinForm R M)
    (hskew : ∀ x y, Q (N x) y + Q x (N y) = 0) (s : R) (x y : M) :
    Q (exchange N s x) (exchange N s y) = Q x y := by
  have hquad := quadratic_term_eq_zero hN Q hskew x y
  simp only [exchange_apply, map_add, map_smul, LinearMap.add_apply, LinearMap.smul_apply,
    smul_eq_mul]
  linear_combination s * hskew x y + s ^ 2 * hquad

/-- The bilinear conservation theorem stated using Mathlib's skew-adjoint predicate. -/
theorem exchange_preserves_bilin_of_isSkewAdjoint {N : Module.End R M} (hN : N * N = 0)
    (Q : LinearMap.BilinForm R M) (hskew : Q.IsSkewAdjoint N) (s : R) (x y : M) :
    Q (exchange N s x) (exchange N s y) = Q x y := by
  apply exchange_preserves_bilin hN Q
  intro u v
  rw [hskew u v]
  simp

end General

section ConcreteCertificate

open S6Shortcuts

/-- The certified square-zero cusp matrix as a module endomorphism. -/
abbrev NEnd : Module.End ℚ V4Q := Matrix.toLin' N

/-- The certified alternating matrix as a bilinear form. -/
abbrev Q0Bilin : LinearMap.BilinForm ℚ V4Q := Matrix.toLinearMap₂' ℚ Q0

/-- The matrix exchange flow corresponding to `1 + sN`. -/
def cuspExchange (s : ℚ) : M4Q := 1 + s • N

private theorem NEnd_square_zero : NEnd * NEnd = 0 := by
  rw [Module.End.mul_eq_comp, ← Matrix.toLin'_mul, N_square_zero]
  simp

private theorem Q0_isSkewAdjoint_N : Q0Bilin.IsSkewAdjoint NEnd := by
  rw [LinearMap.IsSkewAdjoint]
  have hmat : Matrix.IsAdjointPair Q0 Q0 N (-N) := by
    rw [Matrix.IsAdjointPair]
    have h := N_infinitesimally_preserves_Q0
    simpa [Matrix.mul_neg] using eq_neg_of_add_eq_zero_left h
  have hadj := (isAdjointPair_toLinearMap₂' (R := ℚ) Q0 Q0 N (-N)).2 hmat
  simpa using hadj

private theorem cuspExchange_toLin (s : ℚ) :
    Matrix.toLin' (cuspExchange s) = exchange NEnd s := by
  simp [cuspExchange, exchange, Module.End.one_eq_id]

/-- The abstract quadratic-term argument rederives `Nᵀ Q₀ N = 0`. -/
theorem N_quadratic_Q0_term_vanishes_derived : Matrix.transpose N * Q0 * N = 0 := by
  have hform : Q0Bilin.compl₁₂ NEnd NEnd = 0 := by
    apply LinearMap.ext
    intro x
    apply LinearMap.ext
    intro y
    simp only [LinearMap.compl₁₂_apply, LinearMap.zero_apply]
    apply quadratic_term_eq_zero NEnd_square_zero Q0Bilin
    intro u v
    rw [Q0_isSkewAdjoint_N u v]
    simp
  have hmatrix := congrArg (LinearMap.toMatrix₂' ℚ) hform
  simpa using hmatrix

/-- Every rational member of the concrete cusp exchange flow preserves `Q₀`. -/
theorem cuspExchange_preserves_Q0 (s : ℚ) :
    Matrix.transpose (cuspExchange s) * Q0 * cuspExchange s = Q0 := by
  have hform :
      Q0Bilin.compl₁₂ (Matrix.toLin' (cuspExchange s))
          (Matrix.toLin' (cuspExchange s)) = Q0Bilin := by
    apply LinearMap.ext
    intro x
    apply LinearMap.ext
    intro y
    simp only [LinearMap.compl₁₂_apply, cuspExchange_toLin]
    exact exchange_preserves_bilin_of_isSkewAdjoint NEnd_square_zero Q0Bilin
      Q0_isSkewAdjoint_N s x y
  have hmatrix := congrArg (LinearMap.toMatrix₂' ℚ) hform
  simpa using hmatrix

/-- The delivered cusp monodromy is the unit-time square-zero exchange. -/
theorem T0_eq_cuspExchange_one : T0 = cuspExchange 1 := by
  simpa [cuspExchange] using T0_is_I_add_N

/-- Conservation of `Q₀` by `T0`, obtained from the general square-zero flow theorem. -/
theorem T0_preserves_Q0_derived : Matrix.transpose T0 * Q0 * T0 = Q0 := by
  rw [T0_eq_cuspExchange_one]
  exact cuspExchange_preserves_Q0 1

end ConcreteCertificate

end S6.SquareZeroExchange
