[module]
name = "standard-model-from-exceptional-jordan-algebra"
entry = "entry.md"
include = [
  "**/*.md",
  "**/*.tex",
  "**/*.bib",
  "**/*.bbl",
  "**/*.sty",
  "**/*.bst",
  "**/*.pdf",
  "**/*.json",
  "**/*.py"
]
