[module]
name = "stochastic-modes-in-postquantum-gravity"
entry = "entry.md"
include = [
  "**/*.md",
  "**/*.tex",
  "**/*.bib",
  "**/*.bbl",
  "**/*.sty",
  "**/*.bst",
  "**/*.pdf",
  "**/*.json",
  "**/*.py"
]
