import Mathlib

/-!
# Abelianization of a split extension

This file formalizes the unconditional algebraic content of Lemma 6.13.  Coinvariants are encoded
directly as the quotient of the kernel by both its internal commutators and the action-difference
relations.  Thus `Coinvariants φ` is the concrete one-step model of `(Kᵃᵇ)_Q`.

No geometric or analytic existence assertion is made here, and in particular this module makes no
claim that the six-sphere carries a complex structure.
-/

namespace S6.SplitExtension

noncomputable section

variable {K Q : Type*} [Group K] [Group Q]

/-- Relations imposing both abelianization of `K` and triviality of the `Q`-action. -/
def coinvariantRelations (φ : Q →* MulAut K) : Set K :=
  commutatorSet K ∪ Set.range fun qk : Q × K => φ qk.1 qk.2 * qk.2⁻¹

/-- The normal subgroup generated by commutators and action differences. -/
def coinvariantKernel (φ : Q →* MulAut K) : Subgroup K :=
  Subgroup.normalClosure (coinvariantRelations φ)

instance coinvariantKernelNormal (φ : Q →* MulAut K) : (coinvariantKernel φ).Normal := by
  change (Subgroup.normalClosure (coinvariantRelations φ)).Normal
  infer_instance

/-- The coinvariants `(Kᵃᵇ)_Q`, presented directly as a one-step quotient of `K`. -/
abbrev Coinvariants (φ : Q →* MulAut K) := K ⧸ coinvariantKernel φ

private theorem commutator_le_coinvariantKernel (φ : Q →* MulAut K) :
    commutator K ≤ coinvariantKernel φ := by
  rw [commutator_eq_normalClosure]
  exact Subgroup.normalClosure_mono fun _ hz => Or.inl hz

/-- The coinvariant quotient is abelian. -/
instance coinvariantsCommGroup (φ : Q →* MulAut K) : CommGroup (Coinvariants φ) :=
  Group.commGroupOfCenterEqTop (Subgroup.center_eq_top_iff.mpr
    (Subgroup.Normal.quotient_commutative_iff_commutator_le.mpr
      (commutator_le_coinvariantKernel φ)))

/-- The canonical map from the kernel to its coinvariants. -/
def coinvariantOf (φ : Q →* MulAut K) : K →* Coinvariants φ :=
  QuotientGroup.mk' (coinvariantKernel φ)

/-- The action of `Q` becomes trivial in the coinvariant quotient. -/
@[simp]
theorem coinvariantOf_action (φ : Q →* MulAut K) (q : Q) (k : K) :
    coinvariantOf φ (φ q k) = coinvariantOf φ k := by
  apply eq_of_mul_inv_eq_one
  rw [← map_inv, ← map_mul]
  change ((φ q k * k⁻¹ : K) : Coinvariants φ) = 1
  rw [QuotientGroup.eq_one_iff]
  exact Subgroup.subset_normalClosure (Or.inr ⟨(q, k), rfl⟩)

/-- The map from a semidirect product to the two expected abelian factors. -/
def semidirectToFactors (φ : Q →* MulAut K) :
    K ⋊[φ] Q →* Abelianization Q × Coinvariants φ where
  toFun g := (Abelianization.of g.right, coinvariantOf φ g.left)
  map_one' := by simp [coinvariantOf]
  map_mul' g h := by
    ext
    · simp
    · simp [coinvariantOf_action]

/-- The induced map from the abelianization of the semidirect product to the two factors. -/
def abelianizationToFactors (φ : Q →* MulAut K) :
    Abelianization (K ⋊[φ] Q) →* Abelianization Q × Coinvariants φ :=
  Abelianization.lift (semidirectToFactors φ)

private def kernelToSemidirectAbelianization (φ : Q →* MulAut K) :
    K →* Abelianization (K ⋊[φ] Q) :=
  Abelianization.of.comp SemidirectProduct.inl

private theorem coinvariantKernel_le_kernelToSemidirectAbelianization (φ : Q →* MulAut K) :
    coinvariantKernel φ ≤ (kernelToSemidirectAbelianization φ).ker := by
  apply Subgroup.normalClosure_le_normal
  intro z hz
  change z ∈ (kernelToSemidirectAbelianization φ).ker
  rw [MonoidHom.mem_ker]
  rcases hz with hz | ⟨⟨q, k⟩, rfl⟩
  · exact MonoidHom.mem_ker.mp (Abelianization.commutator_subset_ker
      (kernelToSemidirectAbelianization φ) (by
        rw [commutator_eq_closure]
        exact Subgroup.subset_closure hz))
  · simp only [kernelToSemidirectAbelianization, MonoidHom.comp_apply, map_mul, map_inv]
    rw [SemidirectProduct.inl_aut]
    simp [mul_comm]

/-- The coinvariant kernel maps canonically into the semidirect product's abelianization. -/
def coinvariantsToAbelianization (φ : Q →* MulAut K) :
    Coinvariants φ →* Abelianization (K ⋊[φ] Q) :=
  QuotientGroup.lift (coinvariantKernel φ) (kernelToSemidirectAbelianization φ)
    (coinvariantKernel_le_kernelToSemidirectAbelianization φ)

@[simp]
theorem coinvariantsToAbelianization_mk (φ : Q →* MulAut K) (k : K) :
    coinvariantsToAbelianization φ (coinvariantOf φ k) =
      Abelianization.of (SemidirectProduct.inl k : K ⋊[φ] Q) := by
  exact QuotientGroup.lift_mk' _ _ k

@[simp]
theorem abelianizationToFactors_of_inl (φ : Q →* MulAut K) (k : K) :
    abelianizationToFactors φ
        (Abelianization.of (SemidirectProduct.inl k : K ⋊[φ] Q)) =
      (1, coinvariantOf φ k) := by
  rfl

@[simp]
theorem abelianizationToFactors_of_inr (φ : Q →* MulAut K) (q : Q) :
    abelianizationToFactors φ
        (Abelianization.of (SemidirectProduct.inr q : K ⋊[φ] Q)) =
      (Abelianization.of q, 1) := by
  rfl

@[simp]
theorem abelianizationToFactors_coinvariantsToAbelianization_mk
    (φ : Q →* MulAut K) (k : K) :
    abelianizationToFactors φ (coinvariantsToAbelianization φ (coinvariantOf φ k)) =
      (1, coinvariantOf φ k) := by
  rw [coinvariantsToAbelianization_mk, abelianizationToFactors_of_inl]

/-- The map from the two factors back to the semidirect product's abelianization. -/
def factorsToAbelianization (φ : Q →* MulAut K) :
    Abelianization Q × Coinvariants φ →* Abelianization (K ⋊[φ] Q) :=
  (Abelianization.map (SemidirectProduct.inr : Q →* K ⋊[φ] Q)).coprod
    (coinvariantsToAbelianization φ)

/-- Abelianization of a semidirect product splits as quotient abelianization times coinvariants. -/
noncomputable def semidirectAbelianizationEquiv (φ : Q →* MulAut K) :
    Abelianization (K ⋊[φ] Q) ≃* Abelianization Q × Coinvariants φ where
  toFun := abelianizationToFactors φ
  invFun := factorsToAbelianization φ
  map_mul' := map_mul _
  left_inv a := by
    obtain ⟨g⟩ := a
    change factorsToAbelianization φ (semidirectToFactors φ g) = Abelianization.of g
    calc
      _ = Abelianization.of (SemidirectProduct.inl g.left : K ⋊[φ] Q) *
          Abelianization.of (SemidirectProduct.inr g.right : K ⋊[φ] Q) := by
            simp [factorsToAbelianization, semidirectToFactors, mul_comm]
      _ = Abelianization.of (SemidirectProduct.inl g.left * SemidirectProduct.inr g.right) :=
        (map_mul Abelianization.of _ _).symm
      _ = Abelianization.of g := by rw [SemidirectProduct.inl_left_mul_inr_right]
  right_inv a := by
    obtain ⟨q, kbar⟩ := a
    obtain ⟨q⟩ := q
    refine QuotientGroup.induction_on kbar ?_
    intro k
    change abelianizationToFactors φ
        (factorsToAbelianization φ (Abelianization.of q, coinvariantOf φ k)) =
      (Abelianization.of q, coinvariantOf φ k)
    simp [factorsToAbelianization]

section GeneralSplitExtension

variable {E : Type*} [Group E]

/-- The action of the quotient on the kernel supplied by a splitting. -/
def splittingAction (S : GroupExtension K E Q) (s : S.Splitting) : Q →* MulAut K :=
  S.conjAct.comp s.toMonoidHom

/-- The canonical homomorphism from the splitting's semidirect product to the extension group. -/
def semidirectToExtension (S : GroupExtension K E Q) (s : S.Splitting) :
    K ⋊[splittingAction S s] Q →* E :=
  SemidirectProduct.lift S.inl s.toMonoidHom (by
    intro q
    ext k
    exact S.inl_conjAct_comm)

@[simp]
theorem semidirectToExtension_apply (S : GroupExtension K E Q) (s : S.Splitting)
    (a : K ⋊[splittingAction S s] Q) :
    semidirectToExtension S s a = S.inl a.left * s a.right := rfl

private theorem semidirectToExtension_surjective (S : GroupExtension K E Q) (s : S.Splitting) :
    Function.Surjective (semidirectToExtension S s) := by
  intro e
  let q := S.rightHom e
  have hker : e * (s q)⁻¹ ∈ S.rightHom.ker := by
    rw [MonoidHom.mem_ker, map_mul, map_inv, s.rightHom_splitting]
    exact mul_inv_cancel q
  rw [← S.range_inl_eq_ker_rightHom] at hker
  obtain ⟨k, hk⟩ := hker
  refine ⟨⟨k, q⟩, ?_⟩
  change S.inl k * s q = e
  rw [hk]
  group

private theorem semidirectToExtension_injective (S : GroupExtension K E Q) (s : S.Splitting) :
    Function.Injective (semidirectToExtension S s) := by
  intro a b hab
  have hr : a.right = b.right := by
    have h := congrArg S.rightHom hab
    rw [semidirectToExtension_apply, semidirectToExtension_apply] at h
    simpa using h
  apply SemidirectProduct.ext
  · apply S.inl_injective
    apply mul_right_cancel (b := s a.right)
    rw [semidirectToExtension_apply, semidirectToExtension_apply] at hab
    simpa [hr] using hab
  · exact hr

/-- A split exact extension is the semidirect product for the splitting-induced action. -/
noncomputable def splittingMulEquiv (S : GroupExtension K E Q) (s : S.Splitting) :
    K ⋊[splittingAction S s] Q ≃* E :=
  MulEquiv.ofBijective (semidirectToExtension S s)
    ⟨semidirectToExtension_injective S s, semidirectToExtension_surjective S s⟩

/--
Abelianization of a split exact extension is the product of the quotient abelianization and the
coinvariants of the kernel abelianization.
-/
noncomputable def splitExtensionAbelianizationEquiv
    (S : GroupExtension K E Q) (s : S.Splitting) :
    Abelianization E ≃* Abelianization Q × Coinvariants (splittingAction S s) :=
  (splittingMulEquiv S s).symm.abelianizationCongr.trans
    (semidirectAbelianizationEquiv (splittingAction S s))

end GeneralSplitExtension

end
end S6.SplitExtension
