[module]
name = "cosmological-constant-and-general-covariance"
entry = "entry.md"
include = [
  "**/*.md",
  "**/*.tex",
  "**/*.bib",
  "**/*.bbl",
  "**/*.sty",
  "**/*.bst",
  "**/*.pdf",
  "**/*.json",
  "**/*.py"
]
